name: scBridge
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10.6
  - pytorch=1.13.0
  - cudatoolkit=11.8.0 
  - numpy=1.23.3
  - scanpy=1.9.1
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - seaborn=0.12.0
  - harmonypy=0.0.6
  - matplotlib=3.5.3
  - pandas=1.4.4